---
language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19.0

script:
- bin/fetch-configlet
- bin/configlet .
- mix deps.get
- mix test
- "! git grep ' $' -- \\*.exs | grep -v -e 'exercises/diamond/diamond_test.exs'"
sudo: false
